<CaptureScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # White background
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        padding: "50dp"
        spacing: "15dp"

        # -- Logo Area Placeholder --
        Widget:
            size_hint_y: 0.15

        BoxLayout:
            orientation: 'vertical'
            padding: "20dp"
            spacing: "20dp"
            size_hint_y: 0.25

            Widget:
                size_hint_y: 0.2

            Label:
                text: "Place tool on Bed"
                halign: "center"
                valign: "middle"
                text_size: self.size
                font_size: "44sp"
                bold: True
                color: 0, 0, 0, 1
                size_hint_y: None
                height: "72dp"

        # --- CAMERA CONTAINER ---
        RelativeLayout:
            size_hint_y: 0.5

            # 1. The Camera Feed
            Image:
                id: camera_preview
                source: ""
                allow_stretch: True
                keep_ratio: True
                opacity: 0

            # 2. Processing Overlay (Spinner + Text)
            BoxLayout:
                id: processing_overlay
                orientation: 'vertical'
                size_hint: None, None
                size: '180dp', '80dp'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                spacing: "15dp"

                # Hidden by default (opacity 0)
                opacity: 0

                Label:
                    id: loading_label
                    text: "Initializing..."
                    halign: "center"
                    font_size: "24sp"
                    bold: True
                    color: 0.2, 0.6, 0.8, 1

        # -- Spacer --
        Widget:
            size_hint_y: None
            height: "30dp"
            
        # -- Capture Button --
        AppButton:
            id: manual_capture_btn
            text: "MANUAL CAPTURE"
            font_size: "36sp"
            size_hint: 0.975, 0.12
            pos_hint: {"center_x": .5}
            base_color: 0.2, 0.5, 0.85, 1
            down_color: 0.15, 0.4, 0.72, 1
            color: 1, 1, 1, 1
            on_release: root.capture_btn()

        # -- Spacer --
        Widget:
            size_hint_y: None
            height: "30dp"
        
        # -- Bottom Buttons -- 
        BoxLayout:
            orientation: 'horizontal'
            spacing: "12dp"
            size_hint_y: None
            height: '78dp'
            padding: '8dp', '0dp', '8dp', '0dp'

            AppButton:
                text: "CANCEL"
                font_size: "32sp"
                size_hint: .28, 0.8
                base_color: 0.9, 0.17, 0.25, 1  # Red
                down_color: 0.75, 0.12, 0.2, 1
                color: 1, 1, 1, 1
                on_release: root.cancel_transaction()

            AppButton:
                text: "BACK"
                font_size: "32sp"
                size_hint: .28, 0.8
                base_color: 0.4, 0.4, 0.4, 1
                color: 1, 1, 1, 1
                on_release: root.go_back('action selection screen')

        # -- Spacer for the footer--
        Widget:
            size_hint_y: None
            height: "84dp"