<ActionSelectionScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # White background
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        padding: "50dp"
        spacing: "15dp"
        pos_hint: {"center_x": .5, }

        # -- Logo Area Placeholder --
        Widget:
            size_hint_y: 0.65

        # # -- Title --
        # Label:
        #     text: "TOOL-E Checkout"
        #     halign: "center"
        #     font_style: "H3"
        #     theme_text_color: "Primary"
        #     bold: True
        #     size_hint_y: 0.1

        Label:
            text: "Select Action Type"
            halign: "center"
            valign: "middle"
            text_size: self.size
            font_size: "44sp"
            color: 0.15, 0.15, 0.15, 1
            bold: True
            size_hint_y: None
            height: "72dp"

        BoxLayout:
            orientation: 'horizontal'
            padding: "30dp", "15dp"
            spacing: "50dp"
            pos_hint: {"center_x": .5}
            size_hint_y: None
            height: "220dp"

            AppButton:
                text: "BORROW"
                font_size: "44sp"
                size_hint_x: 0.6
                size_hint_y: 0.8
                pos_hint: {"center_x": .5}
                base_color: 0.9, 0.17, 0.25, 1  # Red
                down_color: 0.75, 0.12, 0.2, 1
                color: 1, 1, 1, 1
                on_release: root.select_borrow()

            # AppButton:
            #     text: "CANCEL"
            #     font_size: "28sp"
            #     # background_normal: ''
            #     base_color: 0.9, 0.2, 0.2, 1  # Red
            #     down_color: 0.75, 0.15, 0.15, 1
            #     color: 1,1,1,1
            #     on_press: root.cancel_transaction()

            AppButton:
                text: "RETURN"
                font_size: "44sp"
                size_hint_x: 0.6
                size_hint_y: 0.8
                pos_hint: {"center_x": .5}
                base_color: 0.9, 0.17, 0.25, 1  # Red
                down_color: 0.75, 0.12, 0.2, 1
                color: 1, 1, 1, 1
                on_release: root.select_return()

        # -- Spacer --
        Widget:
            size_hint_y: 0.1

        # -- Spacer --
        Widget:
            size_hint_y: 0.4

        # -- Cancel Button --
        AppButton:
            text: "CANCEL"
            font_size: "36sp"
            size_hint: 1, 0.12
            pos_hint: {"center_x": .5}
            base_color: 0.9, 0.17, 0.25, 1  # Red
            down_color: 0.75, 0.12, 0.2, 1
            color: 1, 1, 1, 1
            on_release: root.cancel_transaction()

        # -- Spacer for the footer--
        Widget:
            size_hint_y: None
            height: "84dp"